export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCESS = "LOGIN_SUCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCESS = "REGISTER_SUCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCESS = "LOAD_USER_SUCESS";
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const OTP_VERIFY_REQUEST = "OTP_VERIFY_REQUEST";
export const OTP_VERIFY_SUCESS = "OTP_VERIFY_SUCESS";
export const OTP_VERIFY_FAIL = "OTP_VERIFY_FAIL";

export const ALL_STUDENTS_REQUEST = "ALL_STUDENTS_REQUEST";
export const ALL_STUDENTS_SUCESS = "ALL_STUDENTS_SUCESS";
export const ALL_STUDENTS_FAIL = "ALL_STUDENTS_FAIL";

export const ADD_MARKS_REQUEST = "ADD_MARKS_REQUEST";
export const ADD_MARKS_SUCESS = "ADD_MARKS_SUCESS";
export const ADD_MARKS_FAIL = "ADD_MARKS_FAIL";

export const STD_INFO_REQUEST = "STD_INFO_REQUEST";
export const STD_INFO_SUCESS = "STD_INFO_SUCESS";
export const STD_INFO_FAIL = "STD_INFO_FAIL";

export const NOTE_ADD_REQUEST = "NOTE_ADD_REQUEST";
export const NOTE_ADD_SUCESS = "NOTE_ADD_SUCESS";
export const NOTE_ADD_FAIL = "NOTE_ADD_FAIL";

export const NOTE_ALL_REQUEST = "NOTE_ALL_REQUEST";
export const NOTE_ALL_SUCESS = "NOTE_ALL_SUCESS";
export const NOTE_ALL_FAIL = "NOTE_ALL_FAIL";

export const TOPPERS_REQUEST = "TOPPERS_REQUEST";
export const TOPPERS_SUCESS = "TOPPERS_SUCESS";
export const TOPPERS_FAIL = "TOPPERS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
